###
// ReviewHandler
GET http://localhost:8080/v1/todo
Accept: application/json

###
// CreateHandler
POST http://localhost:8080/v1/todo
Accept: application/json

{
    "Title":"哒哒",
    "Status":true
}

###
// UpdateHandler
PUT http://localhost:8080/v1/todo/5
Accept: application/json

{
    "Title":"上网",
    "Status":false
}

###
// DeleteHandler
DELETE http://localhost:8080/v1/todo/delete
Accept: application/json

{
    "ids":[5,9]
}

###
// ReviewRecycleHandler
GET http://localhost:8080/v2/todo
Accept: application/json

###
// RestoreAHandler
PUT http://localhost:8080/v2/todo/3
Accept: application/json

###
// RestoreAllHandler
PUT http://localhost:8080/v2/todo
Accept: application/json

###
// EmptyAllRecycleHandler
PUT http://localhost:8080/v2/todo/empty
Accept: application/json

###
// EmptyARecycleHandler
PUT http://localhost:8080/v2/todo/empty/delete
Accept: application/json

{
    "ids":[5,9]
}
