###
//review
POST http://127.0.0.1:8080/v1/todo/review
Accept: application/json

{
    "page":2
}

###
//create
POST http://127.0.0.1:8080/v1/todo
Accept: application/json

{
    "title":"健身",
    "status":true
}

###
//update
PUT  http://127.0.0.1:8080/v1/todo/2
Accept: application/json

{   
    "title":"dance"
}

###
DELETE http://127.0.0.1:8080/v1/todo/delete
Accept: application/json

{
    "ids":[7,9]
}

###
//review recycle
POST http://127.0.0.1:8080/v2/todo/review
Accept: application/json

{
    "page":2
}

###
//restore little recycle
PUT http://127.0.0.1:8080/v2/todo/recycle
Accept: application/json

{
    "ids":[4]
}

###
//restore all recycle
PUT http://127.0.0.1:8080/v2/todo/recycle/all
Accept: application/json

###
//empty little recycle
DELETE  http://127.0.0.1:8080/v2/todo/empty
Accept: application/json

{
    "ids":[8]
}

###
//empty all recycle
DELETE  http://127.0.0.1:8080/v2/todo/empty/all
Accept: application/json